--- #YAML:1.0
name:               Archive-Ar
version:            2.02
abstract:           Interface for manipulating ar archives
author:
    - Jay Bonci <jay@bonci.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Spec:        0
    File::Temp:        0
    Test::MockObject:  0
    Test::More:        0
resources:
    repository:
        type:  git
        url:   https://github.com/jbazik/Archive-Ar.git
        web:   https://github.com/jbazik/Archive-Ar
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  2
