--- #YAML:1.0
name:                Archive-Ar
version:             1.14
abstract:            Interface for manipulating ar archives
license:             ~
author:              
    - Jay Bonci <jay@bonci.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Spec:                    0.83
    File::Temp:                    0
    Test::MockObject:              0.12
    Test::More:                    0.45
    Time::Local:                   1.04
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
